x-aliases:
  - &common_networks
    networks:
      - anfisa
  - &common_parameters
    <<: *common_networks
    env_file:
      - .env
  - &common_druid_parameters
    <<: *common_networks
    image: apache/druid:${DRUID_VERSION}
    env_file:
      - druid.env

networks:
  anfisa:
    driver: bridge
    name: anfisa
    ipam:
      config:
        - subnet:  172.23.0.0/16

services:
  anfisa-frontend:
    user: root
    container_name: anfisa-frontend
    <<: *common_parameters
    image: forome/anfisa-react-client:${ANFISA_FRONTEND_VERSION}
    ports:
      - "${ANFISA_FRONT_PORT}:8080"
    restart: always

  anfisa-backend:
    user: root
    container_name: anfisa-backend
    <<: *common_parameters
    image: forome/anfisa:${ANFISA_BACKEND_VERSION}
    ports:
      - "3041:8089"
    volumes:
      - anfisa-setup:/anfisa/a-setup
      # - ./configs/anfisa.json:/anfisa/anfisa.json
      # - ./configs/igv.dir:/anfisa/igv.dir
    restart: always

  zookeeper:
    user: root
    container_name: anfisa-zookeeper
    <<: *common_parameters
    image: zookeeper:${ZOOKEEPER_VERSION}
    environment:
      - ZOO_MY_ID=1
      - ZK_SERVER_HEAP=128
    restart: always

  coordinator:
    user: root
    container_name: anfisa-coordinator
    <<: *common_druid_parameters
    volumes:
      - druid-data:/opt/data/
      - druid-coordinator:/opt/druid/var
    depends_on:
      - zookeeper
    command:
      - coordinator
    environment:
      - DRUID_XMS=256m
      - DRUID_XMX=2g
    # restart: always

  broker:
    user: root
    container_name: anfisa-broker
    <<: *common_druid_parameters
    volumes:
      - druid-broker:/opt/druid/var
    depends_on:
      - zookeeper
      - coordinator
    command:
      - broker
    environment:
      - DRUID_XMS=512m
      - DRUID_XMX=2g
      - druid_processing_numMergeBuffers=2
      - druid_processing_numThreads=1
    restart: always

  historical:
    user: root
    container_name: anfisa-historical
    <<: *common_druid_parameters
    volumes:
      - druid-data:/opt/data/
      - druid-historical:/opt/druid/var/
    depends_on:
      - zookeeper
      - coordinator
    command:
      - historical
    environment:
      - DRUID_XMS=256m
      - DRUID_XMX=2g
      - druid_processing_numMergeBuffers=2
      - druid_processing_numThreads=2
    restart: always

  middlemanager:
    user: root
    container_name: anfisa-middlemanager
    <<: *common_druid_parameters
    volumes:
      - druid-data:/opt/data/
      - druid-middlemanager:/opt/druid/var
      - anfisa-setup:/anfisa/a-setup
      - anfisa-data:/anfisa/data/
    depends_on:
      - zookeeper
      - coordinator
    command:
      - middleManager
    environment:
      - DRUID_XMS=64m
      - DRUID_XMX=256m
      - druid_indexer_fork_property_druid_processing_buffer_sizeBytes=100000000
      - druid_indexer_fork_property_druid_processing_numThreads=1
    restart: always

  router:
    user: root
    container_name: anfisa-router
    <<: *common_druid_parameters
    volumes:
      - druid-router:/opt/druid/var
    depends_on:
      - zookeeper
      - coordinator
    command:
      - router
    ports:
      - "8888:8888"
    environment:
      - DRUID_XMS=128m
      - DRUID_XMX=256m
    restart: always

  mongo:
    user: root
    container_name: anfisa-mongo
    <<: *common_networks
    volumes:
      - mongo-data:/data/db
    image: mongo:${MONGO_VERSION}
    env_file:
      - mongo.env
    restart: always

volumes:
  anfisa-setup:
  anfisa-data:
  druid-broker:
  druid-middlemanager:
  druid-coordinator:
  druid-router:
  druid-historical:
  druid-data:
  mongo-data:
