apiVersion: v1
kind: Secret
metadata:
  name: anfisa-front-registry
  labels:
    {{- include "anfisa-front.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "anfisa-front.imagePullSecret" . }}