apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: anfisa
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsGroup: 0
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          ports:
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
          # command: [ "/bin/bash" ]
          # args: [ "-c", "sleep infinity" ]
          # command: [ "/entrypoint.sh" ]
          # args: [ "/usr/local/bin/supervisord" ]
          volumeMounts:
          - name: forome-anfisa
            mountPath: /data/anfisa/
          - name: anfisa-workdir
            mountPath: /anfisa/a-setup/
          - name: forome-datasets-pvc
            mountPath: /mnt/forome-datasets
          - name: igv-dir
            mountPath: /anfisa/igv.dir
            subPath: igv.dir
      volumes:
      - name: forome-anfisa
        persistentVolumeClaim:
          claimName: forome-anfisa-s3-pvc
      - name: anfisa-workdir
        persistentVolumeClaim:
          claimName: anfisa-workdir-claim
      - name: forome-datasets-pvc
        persistentVolumeClaim:
          claimName: forome-datasets-pvc
      - name: igv-dir
        configMap:
          name: igv-dir
          defaultMode: 0666
      terminationGracePeriodSeconds: 5
