

anfisa-back:
  persistent:
    foromeAnfisaS3:
      size: 100Gi
      storageClassName:
    anfisaWorkdir:
      size: 100Gi
      storageClassName:
    foromeDatasets:
      size: 100Gi
      storageClassName:

anfisa-front:
  image:
    repository: forome.azurecr.io/anfisa-react-client
    tag: v0.8.43
    pullPolicy: IfNotPresent

  env:
    - name: URL_BACKEND
      value: http://anfisa-backend
    - name: REACT_APP_URL_BACKEND
      value: https://anfisa.example.com/app

  ingress:
    enabled: false
    className: ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: anfisa.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: anfisa.example.com
      hosts:
        - anfisa.example.com
